MERGE INTO `tgrouprefdataeng` USING DUAL ON (`GROUPTYPE`='TRIBE' AND `GROUPVALUE`='RCM') 
WHEN NOT MATCHED THEN
INSERT(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('TRIBE','RCM','Referntial Client Management','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

MERGE INTO `tgrouprefdataeng` USING DUAL ON (`GROUPTYPE`='FT' AND `GROUPVALUE`='SNO') 
WHEN NOT MATCHED THEN
INSERT(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('FT','SNO','Referntial Client Management','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

MERGE INTO `tgrouprefdataeng` USING DUAL ON (`GROUPTYPE`='FT' AND `GROUPVALUE`='ENO') 
WHEN NOT MATCHED THEN
INSERT(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('FT','ENO','Referntial Client Management','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);