DROP TABLE IF EXISTS TCARDCHANGESENG;
DROP TABLE IF EXISTS TSTATUSESENG;
DROP TABLE IF EXISTS TGROUPADMINSENG;
DROP TABLE IF EXISTS TCARDSENG;
DROP TABLE IF EXISTS TBOOKMARKGROUPSENG;
DROP TABLE IF EXISTS TGROUPREFDATAENG;
DROP TABLE IF EXISTS TBOOKMARKSENG;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table TBOOKMARKSENG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TBOOKMARKSENG (
  BOOKMARKID BIGINT NOT NULL AUTO_INCREMENT,
  BOOKMARKURL VARCHAR(1000) NOT NULL,
  SHORTURL VARCHAR(250) NOT NULL,
  EXPIRYDATE DATETIME NOT NULL,
  OPECRE VARCHAR(250) NOT NULL,
  DATCRE TIMESTAMP NOT NULL,
  OPEMOD VARCHAR(250) NOT NULL,
  DATMOD TIMESTAMP NULL NULL,
  PRIMARY KEY (BOOKMARKID),
  UNIQUE INDEX SHORTURL_UNIQUE_TBOOKMARKSENG (SHORTURL ASC));


-- -----------------------------------------------------
-- Table TGROUPREFDATAENG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TGROUPREFDATAENG (
  GROUPTYPE VARCHAR(15) NOT NULL,
  GROUPVALUE VARCHAR(30) NOT NULL,
  GROUPVALUEDESC VARCHAR(60) NULL,
  OPECRE VARCHAR(250) NOT NULL,
  DATCRE TIMESTAMP NOT NULL,
  OPEMOD VARCHAR(250) NOT NULL,
  DATMOD TIMESTAMP NULL NULL,
  PRIMARY KEY (GROUPTYPE, GROUPVALUE));


-- -----------------------------------------------------
-- Table TBOOKMARKGROUPSENG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TBOOKMARKGROUPSENG (
  GROUPID BIGINT NOT NULL AUTO_INCREMENT,
  GROUPTYPE VARCHAR(15) NOT NULL,
  GROUPVALUE VARCHAR(30) NOT NULL,
  OPECRE VARCHAR(250) NOT NULL,
  DATCRE TIMESTAMP NOT NULL,
  OPEMOD VARCHAR(250) NOT NULL,
  DATMOD TIMESTAMP NULL NULL,
  PRIMARY KEY (GROUPID),
   UNIQUE INDEX GROUPTYPE_GROUPVALUE_UNIQUE (GROUPTYPE ASC, GROUPVALUE ASC));

-- -----------------------------------------------------
-- Table TCARDSENG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TCARDSENG (
  CARDID BIGINT NOT NULL AUTO_INCREMENT,
  BOOKMARKURL VARCHAR(1000) NOT NULL,
  CARDTITLE VARCHAR(45) NOT NULL,
  CARDDESC VARCHAR(250) NOT NULL,
  IMAGEURL VARCHAR(50) NOT NULL,
  SHORTURL VARCHAR(250) NOT NULL,
  GROUPID BIGINT NOT NULL,
  PUBLISH VARCHAR(1) NOT NULL,
  OPECRE VARCHAR(250) NOT NULL,
  DATCRE TIMESTAMP NOT NULL,
  OPEMOD VARCHAR(250) NOT NULL,
  DATMOD TIMESTAMP NULL NULL,
  PRIMARY KEY (CARDID),
  UNIQUE INDEX SHORTURL_UNIQUE (SHORTURL ASC));


-- -----------------------------------------------------
-- Table TGROUPADMINSENG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TGROUPADMINSENG (
  GROUPUSERID BIGINT NOT NULL AUTO_INCREMENT,
  GROUPID BIGINT NOT NULL,
  USERID VARCHAR(100) NOT NULL,
  OPECRE VARCHAR(250) NOT NULL,
  DATCRE TIMESTAMP NOT NULL,
  OPEMOD VARCHAR(250) NOT NULL,
  DATMOD TIMESTAMP NULL NULL,
  PRIMARY KEY (GROUPUSERID));


-- -----------------------------------------------------
-- Table TSTATUSESENG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TSTATUSESENG (
  STATUSCODE VARCHAR(1) NOT NULL,
  STATUSVALUE VARCHAR(10) NOT NULL,
  PRIMARY KEY (STATUSCODE));


-- -----------------------------------------------------
-- Table TCARDCHANGESENG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TCARDCHANGESENG (
  CARDCHANGEID BIGINT NOT NULL,
  CARDID BIGINT NOT NULL,
  BOOKMARKURL VARCHAR(1000) NOT NULL,
  CARDTITLE VARCHAR(45) NOT NULL,
  CARDDESC VARCHAR(250) NULL,
  IMAGEURL VARCHAR(50) NULL,
  SHORTURL VARCHAR(45) NULL,
  GROUPID BIGINT NULL,
  STATUS VARCHAR(1) NOT NULL,
  OPECRE VARCHAR(250) NOT NULL,
  DATCRE TIMESTAMP NOT NULL,
  OPEMOD VARCHAR(250) NOT NULL,
  DATMOD TIMESTAMP NULL NULL,
  PRIMARY KEY (CARDCHANGEID));
