-- -----------------------------------------------------
-- Data for table `TSTATUSESENG`
-- -----------------------------------------------------
--INSERT INTO `TSTATUSESENG` (`STATUSCODE`, `STATUSVALUE`) VALUES ('A', 'APPROVED');
--INSERT INTO `TSTATUSESENG` (`STATUSCODE`, `STATUSVALUE`) VALUES ('S', 'SUBMITTED');
--INSERT INTO `TSTATUSESENG` (`STATUSCODE`, `STATUSVALUE`) VALUES ('D', 'DENIED');

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('TRIBE','RCM','Referntial Client Management','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('FT','SNO','Strcture and Oraganization','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('FT','ENO','Environmental and Others','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('FT','PNA','Payment and Accounts','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('FT','KYC','Know Your Customer','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('FT','SCOW','SGCIB Client Onboarding team','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('APPLICATION','BDR','Referential System','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);

INSERT INTO `tgrouprefdataeng`
(`GROUPTYPE`,`GROUPVALUE`,`GROUPVALUEDESC`,`OPECRE`,`DATCRE`,`OPEMOD`,`DATMOD`)
VALUES('APPLICATION','MAESTRO','Maestro Application','bookmark',CURRENT_TIMESTAMP,'bookmark',CURRENT_TIMESTAMP);
